//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignTask
    {
        public int AssignTaskID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> HoursWorked { get; set; }
        public Nullable<double> AmountWorked { get; set; }
    }
}
