//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateRole
    {
        public int CreateRoleID { get; set; }
        public string RoleCategory { get; set; }
        public Nullable<double> RoleRate { get; set; }
    }
}
