//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateTask
    {
        public int CreateTaskID { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<int> TaskHours { get; set; }
        public Nullable<int> RoleID { get; set; }
    }
}
